#!/bin/sh
BasePath=$(cd `dirname $0`; pwd)
BasePath=`dirname ${BasePath}`
BasePath=`dirname ${BasePath}`

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".vue\{0,1\}$")
if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi
PASS=true
echo "Validating Javascript:"
# Check for eslint
which ${BasePath}/Code/Frontend/node_modules/.bin/eslint &> /dev/null
if [[ "$?" == 1 ]]; then
  echo -e "Please install ESlint"
  exit 1
fi
for FILE in $STAGED_FILES
do
  ${BasePath}/Code/Frontend/node_modules/.bin/eslint "$FILE" -c ${BasePath}/Code/Frontend/.eslintrc.js
  if [[ "$?" == 0 ]]; then
    echo "ESLint Passed: $FILE"
  else
    echo "ESLint Failed: $FILE"
    PASS=false
  fi
done
echo "Javascript validation completed!"
if ! $PASS; then
  echo "COMMIT FAILED: Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again."
  exit 1
else
  echo "COMMIT SUCCEEDED"
fi
exit $?